{
  "comments": [
    {
      "key": {
        "uuid": "a7e000b0_f70d93c2",
        "filename": "catalog-be/sdc-backend-init/Dockerfile",
        "patchSetId": 4
      },
      "lineNbr": 1,
      "author": {
        "id": 15
      },
      "writtenOn": "2020-06-16T10:08:50Z",
      "side": 1,
      "message": "Hey, sorry if it\u0027s a stupid question, but where do you find this image ? I don\u0027t see a 1.7.0 tag on sdc-docker-base ðŸ˜•\nAnd subsequent question for anyone out there, am I right in guessing that https://jenkins.onap.org/view/sdc/job/sdc-master-verify-java/configure doesn\u0027t build the docker images ? I don\u0027t see the docker profile being specified",
      "revId": "750e9c2cbd718d507761b5e97ddd1ad2294ee307",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "4e1d90ad_ef5b017b",
        "filename": "catalog-be/sdc-backend-init/Dockerfile",
        "patchSetId": 4
      },
      "lineNbr": 1,
      "author": {
        "id": 5335
      },
      "writtenOn": "2020-06-16T11:04:32Z",
      "side": 1,
      "message": "This is the actual very good question :) This image should be built by the maven in the https://gerrit.onap.org/r/admin/repos/sdc/sdc-docker-base repository.\n\nLike you can see in the comment under review: \nhttps://gerrit.onap.org/r/c/sdc/sdc-docker-base/+/108763\n(changes that provide python3 for uses by this commit).\n\nCurrently, the image is produced with tag 1.6.1-SNAPSHOT-20200615T080732Z. So this should be adjusted.",
      "parentUuid": "a7e000b0_f70d93c2",
      "revId": "750e9c2cbd718d507761b5e97ddd1ad2294ee307",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "62b1f2b8_84e49be6",
        "filename": "catalog-be/src/main/resources/scripts/sdcBePy/users/run.py",
        "patchSetId": 4
      },
      "lineNbr": 9,
      "author": {
        "id": 5
      },
      "writtenOn": "2020-06-17T14:39:44Z",
      "side": 1,
      "message": "I got an error when running this locally, seems this is not defined if i\u0027m not mistaken :\n      File \"/home/onap/.local/lib/python3.8/site-packages/sdcBePy-1.7-py3.8.egg/sdcBePy/users/run.py\", line 9, in \u003cmodule\u003e\n        from sdcBePy.common.healthCheck import check_backend, RETRY_ATTEMPTS\n    ModuleNotFoundError: No module named \u0027sdcBePy.common.healthCheck\u0027",
      "range": {
        "startLine": 8,
        "startChar": 43,
        "endLine": 9,
        "endChar": 31
      },
      "revId": "750e9c2cbd718d507761b5e97ddd1ad2294ee307",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "61e361b6_2d8e3227",
        "filename": "catalog-be/src/main/resources/scripts/sdcBePy/users/run.py",
        "patchSetId": 4
      },
      "lineNbr": 9,
      "author": {
        "id": 5
      },
      "writtenOn": "2020-06-17T14:47:29Z",
      "side": 1,
      "message": "done in the other related reviews",
      "parentUuid": "62b1f2b8_84e49be6",
      "range": {
        "startLine": 8,
        "startChar": 43,
        "endLine": 9,
        "endChar": 31
      },
      "revId": "750e9c2cbd718d507761b5e97ddd1ad2294ee307",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}